# Generated by Django 4.2 on 2023-04-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True, default="hotel.jpg", null=True, upload_to="hotels"
            ),
        ),
    ]
